Feature/app 390 fix runtime errors
CirclesUBI/o-platform pull request #374
Opened 2023-07-25 08:29 UTC by ingoCollatz

2023-07-25 09:23 UTC, codeho requested changes

2023-07-25 09:23 UTC, codeho commented on shell/src/shared/openLogin.ts
> +      async logout(): Promise<void> { },
this is not doing anything... why did you add it? :)

2023-07-25 09:23 UTC, codeho commented on shell/src/shared/processes/shellProcess.ts
> +            console.log(`Running child process ${processId}: `, sm);
remove console.log

2023-07-25 09:23 UTC, codeho commented on shell/src/main.ts
> +      console.log(`Starting process (id: ${processId}) with definition:`, definition, definition.stateMachine("debug"));
remove console.log

2023-07-27 17:44 UTC, codeho approved these changes

2023-07-27 18:25 UTC, jaensen approved these changes
Looks good. Only one remark:
In one case you used 
```
import { get } from 'svelte/store'
```
and then 
```
      const $me = get(me)
```
in the other case you left
```
    let $me: Profile;
    me.subscribe((m) => ($me = m))();
```
which in principle is fine. But using the `get()` shorthand everywhere would surely have been nicer (I know, the latter was by me 😂).

2023-07-27 22:13 UTC, merged